// This file is auto-generated. Do not edit this file manually.
//
// Disable formatting for this file to avoid linting errors.
// tslint:disable
// @ts-nocheck
/* eslint-disable */

import dotenv from 'dotenv';
let env = dotenv.config();

import * as f from "./function"
import "./impls"

const BamlClient = {
  ClassifyMessage: f.ClassifyMessage,
  ExtractResume: f.ExtractResume,
}

export default BamlClient

