// This file is auto-generated. Do not edit this file manually.
//
// Disable formatting for this file to avoid linting errors.
// tslint:disable
// @ts-nocheck
/* eslint-disable */

import { loadEnvVars } from "@boundaryml/baml-core"
import * as f from "./function"
import "./impls"

loadEnvVars()

const BamlClient = {
  ClassifyMessage: f.ClassifyMessage,
  ExtractResume: f.ExtractResume,
}

export default BamlClient

export { DeserializerException } from "@boundaryml/baml-core/deserializer/diagnostics"


